module;
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/cfg/argv.h>
#include <spdlog/cfg/env.h>
#include <spdlog/cfg/helpers.h>
#include <spdlog/formatter.h>
#include <spdlog/mdc.h>
#include <spdlog/pattern_formatter.h>
#include <spdlog/sinks/android_sink.h>
#include <spdlog/sinks/ansicolor_sink.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/callback_sink.h>
#include <spdlog/sinks/daily_file_sink.h>
#include <spdlog/sinks/dist_sink.h>
#include <spdlog/sinks/dup_filter_sink.h>
#include <spdlog/sinks/hourly_file_sink.h>
//#include <spdlog/sinks/kafka_sink.h>
//#include <spdlog/sinks/mongo_sink.h>
#include <spdlog/sinks/msvc_sink.h>
#include <spdlog/sinks/null_sink.h>
#include <spdlog/sinks/ostream_sink.h>
//#include <spdlog/sinks/qt_sinks.h>
#include <spdlog/sinks/ringbuffer_sink.h>
#include <spdlog/sinks/rotating_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/stdout_sinks.h>
//#include <spdlog/sinks/syslog_sink.h>
//#include <spdlog/sinks/systemd_sink.h>
#include <spdlog/sinks/tcp_sink.h>
#include <spdlog/sinks/udp_sink.h>
#include <spdlog/sinks/wincolor_sink.h>
#include <spdlog/sinks/win_eventlog_sink.h>
#include <spdlog/stopwatch.h>
export module spdlog;

export namespace spdlog
{
    using ::spdlog::apply_all;
    using ::spdlog::apply_logger_env_levels;
    using ::spdlog::async_factory;
    using ::spdlog::async_factory_nonblock;
    using ::spdlog::async_logger;
    using ::spdlog::async_overflow_policy;
    using ::spdlog::basic_logger_mt;
    using ::spdlog::basic_logger_st;
    using ::spdlog::callback_logger_mt;
    using ::spdlog::callback_logger_st;
    namespace cfg
    {
        namespace helpers
        {
            using ::spdlog::cfg::helpers::load_levels;
        }
        using ::spdlog::cfg::load_argv_levels;
        using ::spdlog::cfg::load_env_levels;
    }
    using ::spdlog::color_mode;
    using ::spdlog::create;
    using ::spdlog::create_async;
    using ::spdlog::create_async_nb;
    using ::spdlog::critical;
    using ::spdlog::custom_flag_formatter;
    using ::spdlog::custom_log_callback;
    using ::spdlog::daily_logger_format_mt;
    using ::spdlog::daily_logger_format_st;
    using ::spdlog::daily_logger_mt;
    using ::spdlog::daily_logger_st;
    using ::spdlog::debug;
    using ::spdlog::default_factory;
    using ::spdlog::default_logger;
    using ::spdlog::default_logger_raw;
    using ::spdlog::disable_backtrace;
    using ::spdlog::drop;
    using ::spdlog::drop_all;
    using ::spdlog::dump_backtrace;
    using ::spdlog::enable_backtrace;
    using ::spdlog::error;
    using ::spdlog::err_handler;
    using ::spdlog::filename_t;
    using ::spdlog::file_event_handlers;
    using ::spdlog::flush_every;
    using ::spdlog::flush_on;
    using ::spdlog::formatter;
    using ::spdlog::format_string_t;
    using ::spdlog::get;
    using ::spdlog::get_level;
    using ::spdlog::hourly_logger_mt;
    using ::spdlog::hourly_logger_st;
    using ::spdlog::info;
    using ::spdlog::initialize_logger;
    using ::spdlog::init_thread_pool;
    using ::spdlog::is_convertible_to_any_format_string;
    using ::spdlog::is_convertible_to_basic_format_string;
    //using ::spdlog::kafka_logger_async_mt;
    //using ::spdlog::kafka_logger_async_st;
    //using ::spdlog::kafka_logger_mt;
    //using ::spdlog::kafka_logger_st;
    namespace level
    {
        using ::spdlog::level::from_str;
        using ::spdlog::level::level_enum;
        using ::spdlog::level::to_short_c_str;
        using ::spdlog::level::to_string_view;
    }
    using ::spdlog::level_t;
    using ::spdlog::log;
    using ::spdlog::logger;
    using ::spdlog::log_clock;
    using ::spdlog::mdc;
    using ::spdlog::memory_buf_t;
    //using ::spdlog::mongo_logger_mt;
    //using ::spdlog::mongo_logger_st;
    using ::spdlog::null_logger_mt;
    using ::spdlog::null_logger_st;
    using ::spdlog::pattern_formatter;
    using ::spdlog::pattern_time_type;
    //using ::spdlog::qt_color_logger_mt;
    //using ::spdlog::qt_color_logger_st;
    //using ::spdlog::qt_logger_mt;
    //using ::spdlog::qt_logger_st;
    using ::spdlog::register_logger;
    using ::spdlog::register_or_replace;
    using ::spdlog::rotating_logger_mt;
    using ::spdlog::rotating_logger_st;
    using ::spdlog::set_automatic_registration;
    using ::spdlog::set_default_logger;
    using ::spdlog::set_error_handler;
    using ::spdlog::set_formatter;
    using ::spdlog::set_level;
    using ::spdlog::set_pattern;
    using ::spdlog::should_log;
    using ::spdlog::shutdown;
    namespace sinks
    {
        using ::spdlog::sinks::ansicolor_stderr_sink_mt;
        using ::spdlog::sinks::ansicolor_stderr_sink_st;
        using ::spdlog::sinks::ansicolor_stdout_sink_mt;
        using ::spdlog::sinks::ansicolor_stdout_sink_st;
        using ::spdlog::sinks::basic_file_sink_mt;
        using ::spdlog::sinks::basic_file_sink_st;
        using ::spdlog::sinks::callback_sink_mt;
        using ::spdlog::sinks::callback_sink_st;
        using ::spdlog::sinks::daily_filename_calculator;
        using ::spdlog::sinks::daily_filename_format_calculator;
        using ::spdlog::sinks::daily_file_format_sink_mt;
        using ::spdlog::sinks::daily_file_format_sink_st;
        using ::spdlog::sinks::daily_file_sink_mt;
        using ::spdlog::sinks::daily_file_sink_st;
        using ::spdlog::sinks::dist_sink_mt;
        using ::spdlog::sinks::dist_sink_st;
        using ::spdlog::sinks::dup_filter_sink_mt;
        using ::spdlog::sinks::dup_filter_sink_st;
        using ::spdlog::sinks::hourly_filename_calculator;
        using ::spdlog::sinks::hourly_file_sink_mt;
        using ::spdlog::sinks::hourly_file_sink_st;
        //using ::spdlog::sinks::kafka_sink_config;
        //using ::spdlog::sinks::kafka_sink_mt;
        //using ::spdlog::sinks::kafka_sink_st;
        //using ::spdlog::sinks::mongo_sink_mt;
        //using ::spdlog::sinks::mongo_sink_st;
        using ::spdlog::sinks::msvc_sink_mt;
        using ::spdlog::sinks::msvc_sink_st;
        using ::spdlog::sinks::null_sink_mt;
        using ::spdlog::sinks::null_sink_st;
        using ::spdlog::sinks::ostream_sink_mt;
        using ::spdlog::sinks::ostream_sink_st;
        //using ::spdlog::sinks::qt_color_sink_mt;
        //using ::spdlog::sinks::qt_color_sink_st;
        //using ::spdlog::sinks::qt_sink_mt;
        //using ::spdlog::sinks::qt_sink_st;
        using ::spdlog::sinks::ringbuffer_sink_mt;
        using ::spdlog::sinks::ringbuffer_sink_st;
        using ::spdlog::sinks::rotating_file_sink_mt;
        using ::spdlog::sinks::rotating_file_sink_st;
        using ::spdlog::sinks::stderr_color_sink_mt;
        using ::spdlog::sinks::stderr_color_sink_st;
        using ::spdlog::sinks::stderr_sink_mt;
        using ::spdlog::sinks::stderr_sink_st;
        using ::spdlog::sinks::stdout_color_sink_mt;
        using ::spdlog::sinks::stdout_color_sink_st;
        using ::spdlog::sinks::stdout_sink_mt;
        using ::spdlog::sinks::stdout_sink_st;
        //using ::spdlog::sinks::syslog_sink_mt;
        //using ::spdlog::sinks::syslog_sink_st;
        //using ::spdlog::sinks::systemd_sink_mt;
        //using ::spdlog::sinks::systemd_sink_st;
        using ::spdlog::sinks::tcp_sink_config;
        using ::spdlog::sinks::tcp_sink_mt;
        using ::spdlog::sinks::tcp_sink_st;
        using ::spdlog::sinks::udp_sink_config;
        using ::spdlog::sinks::udp_sink_mt;
        using ::spdlog::sinks::udp_sink_st;
        using ::spdlog::sinks::wincolor_stderr_sink_mt;
        using ::spdlog::sinks::wincolor_stderr_sink_st;
        using ::spdlog::sinks::wincolor_stdout_sink_mt;
        using ::spdlog::sinks::wincolor_stdout_sink_st;
        using ::spdlog::sinks::windebug_sink_mt;
        using ::spdlog::sinks::windebug_sink_st;
        using ::spdlog::sinks::win_eventlog_sink_mt;
        using ::spdlog::sinks::win_eventlog_sink_st;
    }
    using ::spdlog::sinks_init_list;
    using ::spdlog::sink_ptr;
    using ::spdlog::source_loc;
    using ::spdlog::spdlog_ex;
    using ::spdlog::stderr_color_mt;
    using ::spdlog::stderr_color_st;
    using ::spdlog::stderr_logger_mt;
    using ::spdlog::stderr_logger_st;
    using ::spdlog::stdout_color_mt;
    using ::spdlog::stdout_color_st;
    using ::spdlog::stdout_logger_mt;
    using ::spdlog::stdout_logger_st;
    using ::spdlog::stopwatch;
    using ::spdlog::string_view_t;
    using ::spdlog::swap;
    using ::spdlog::synchronous_factory;
    //using ::spdlog::syslog_logger_mt;
    //using ::spdlog::syslog_logger_st;
    //using ::spdlog::systemd_logger_mt;
    //using ::spdlog::systemd_logger_st;
    using ::spdlog::thread_pool;
    using ::spdlog::throw_spdlog_ex;
    using ::spdlog::trace;
    using ::spdlog::udp_logger_mt;
    using ::spdlog::warn;
}
